service: puppeteer-lambda

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  puppeteer:
    handler: handler.hello
    events:
      - http:
          path: url
          method: get
          request:
            application/json: '{ "url" : "$input.params(''url'')" }'
          cors: true
